### ISSUE TITLE
Intro to React Hooks

### ISSUE THREAD

**Issue by danivm** [jscodersbcn/talks#2]
###### Intro to React Hooks

**Resumen**

Los Hooks son una nueva API de React que va a cambiar la forma que tenemos de declarar componentes y nos van a permitir gestionar el estado en componentes funcionales (entre otras características).

**Descripción**

En el meetup haremos una introducción teórica para entender el contexto y la necesidad los Hooks. Después, veremos unos ejemplos prácticos de código donde refactorizamos varios componentes.

**Requisitos**

Conocimientos básicos en:
- Javascript
- React

**Duración aproximada**

 - 2/3 h

**Nivel**

Básico - Intermedio

**Recursos**

[React Hooks](https://reactjs.org/docs/hooks-intro.html)

**Speaker Bio**

Daniel Muñoz - Frontend Developer
Schibted Spain (Fotocasa)

**Comment by jalbertsr** [comment]
Amazing talk! https://www.meetup.com/es-ES/js-coders/events/258865309/
