### ISSUE TITLE
StencilJS

### ISSUE THREAD

**Issue by ghost** [jscodersbcn/talks#3]
**Resumen**

![stenciljs](https://www.joshmorony.com/media/2018/01/stencil-ecosystem-chart.png)

StencilJS es una alternativa que tenemos a la hora de crear nuestros componentes. No se trata de otro framework ni de otra librería, desde su propia web se definen como: "The magical, reusable web component compiler".

**Descripción**
 
Habrá un breve repaso/introducción a como declarariamos un componente con la API nativa de WebComponents, y posteriormente empezaríamos con StencilJS. Continuaremos desde que nos aporta este ''compilador'' hasta un ejemplo (futuro repositirio con los ejemplos) de su API y para finalizar un caso de una libreria puesta en producción implementada con StencilJS y D3.js.

**Requisitos**

Conocimientos básicos en:

- JavaScript / TypeScript

**Duración aproximada**

still undefined (1h/1:30h aprox)

**Nivel**

Básico - Intermedio

**Recursos**

[StencilJS](https://stenciljs.com/)

**Speaker Bio**

Edgar Ordóñez - Software Engineer 
kiwi.com (Barcelona)

**Comment by jalbertsr** [comment]
Great talk! https://www.meetup.com/es-ES/js-coders/events/260911764/
